#!/bin/bash
# SBATCH --partition=par-multi 
#SBATCH --partition=par-single
# SBATCH --partition=test
#SBATCH --ntasks=16
# SBATCH --partition=high-mem
# SBATCH --mem=64GB
# SBATCH --partition=short-serial
# SBATCH --partition=short-serial-4hr
# SBATCH --account=short4hr 
#SBATCH -o %j.out 
#SBATCH -e %j.err
#SBATCH --time=44:00:00

# load python3 module
# module add jaspy

source /home/users/hkhatri/miniconda3/bin/activate

# Execute python script

# srun python Seasonal_Surface_Diag_NAO.py

# srun python Timeseries_Gyre_MHT.py

# srun python Annual_Heat_Overturning.py

# srun python Atmos_6month_timeseries.py

# srun python Ocean_6month_timeseries.py

# srun python Timeseries_SST_Heat_budget.py

# srun python Tracer_Depth_Lon.py

# srun python Timeseries_Overturning_MHT.py 




mpirun python Timeseries_Overturning_MHT_extreme_MHT_Psi.py
