#!/bin/bash
# SBATCH --partition=par-multi 
# SBATCH --partition=par-single
# SBATCH --partition=test
# SBATCH --ntasks=16
#SBATCH --partition=high-mem
#SBATCH --mem=64GB
# SBATCH --partition=short-serial
# SBATCH --partition=short-serial-4hr
# SBATCH --account=short4hr 
#SBATCH -o %j.out 
#SBATCH -e %j.err
#SBATCH --time=24:00:00

source /home/users/hkhatri/miniconda3/bin/activate

# Execute python script

# srun python3 Combine_Data_Ocean_Surface_grid_T.py

srun python Combine_Data_Overturning.py

# srun python3 Combine_Data_Atmosphere_var.py

# mpirun python Combine_overturning_transport_sigma.py

# module purge 
