#!/bin/bash 
#SBATCH --partition=par-single
#SBATCH --ntasks=8
# SBATCH --partition=high-mem
# SBATCH --partition=short-serial
# SBATCH --partition=short-serial-4hr
# SBATCH --account=short4hr 
#SBATCH -o %j.out 
#SBATCH -e %j.err
#SBATCH --time=24:00:00

# load python3 module
module load jaspy #/3.7/r20181219

# Execute python script

# srun python3 Combine_Data_Ocean_Surface_grid_T.py
# srun python3 Combine_Data_Overturning.py
# srun python3 Combine_Data_Atmosphere_var.py

# srun python3 Drift_Overturning.py
# srun python3 Drift_ocean_var_DCPP2016.py
# srun python3 Drift_atmosphere_var_DCPP2016.py
srun python3 Drift_Monthly_DCPP_2016.py

# srun python3 Drift_var_ocean.py
# srun python3 Drift_var_atmosphere.py
# srun python3 Drift_combine_yearwise.py

# srun python3 Anomaly_DCPP2016.py

# module load jaspy # latest version

# srun python3 Drift_Trend_compute.py

module purge 
