#!/bin/bash
#SBATCH --partition=par-multi 
# SBATCH --partition=par-single
#SBATCH --ntasks=16
# SBATCH --partition=high-mem
# SBATCH --mem=64GB
# SBATCH --partition=short-serial
# SBATCH --partition=short-serial-4hr
# SBATCH --account=short4hr 
#SBATCH -o %j.out 
#SBATCH -e %j.err
#SBATCH --time=24:00:00

# load python3 module
#module add jaspy #/3.7/r20181219

source /home/users/hkhatri/.conda/envs/py-xgcm-slurm/bin/activate
module load eb/OpenMPI/gcc/4.0.0

# Execute python script

# srun python3 Combine_Data_Ocean_Surface_grid_T.py
# srun python3 Combine_Data_Overturning.py
# srun python3 Combine_Data_Atmosphere_var.py

# srun python3 Drift_Overturning.py
mpirun -n 16 python Drift_ocean_var_DCPP2016.py
# srun python Drift_atmosphere_var_DCPP2016.py
# srun python3 Drift_Monthly_DCPP_2016.py
# mpirun -n 8 python Drift_ocean_derived_var_DCPP2016.py

# srun python Drift_var_ocean.py
# srun python3 Drift_var_atmosphere.py
# srun python3 Drift_combine_yearwise.py

# mpirun -n 16 python Anomaly_DCPP2016.py
# srun python Anomaly_SLP_NAO_compute.py

#mpirun -n 8 python Composite_Diagnostics_NAO_phases.py

# srun python Correlation_NAO_ocean_var.py

# srun python3 Drift_Trend_compute.py

# module purge 
