#!/bin/bash 
#SBATCH --partition=par-single
#SBATCH --ntasks=4
# SBATCH --partition=short-serial
# SBATCH --partition=short-serial-4hr
# SBATCH --account=short4hr 
#SBATCH -o %j.out 
#SBATCH -e %j.err
#SBATCH --time=12:00:00

# load python3 module
module load jaspy/3.7/r20181219

# Execute python script

# srun python3 Combine_Data_Ocean_Surface_grid_T.py

# srun python3 Combine_Data_Overturning.py

# srun python3 Combine_Data_Atmosphere_var.py

srun python3 Drift_Overturning.py 
